name: linux server deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.76.5'
          extended: true

      - name: Build
        run: |
          npm prune
          npm i -D postcss postcss-cli
          npm i -D autoprefixer
          git submodule add --force https://github.com/google/docsy.git themes/docsy
          git submodule update --init --recursive                    
          hugo --minify
          ls ./public -l

#      - name: Copy file via ssh password
#          uses: appleboy/scp-action@master
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.USERNAME }}
#            key: ${{ secrets.KEY }}
#            port: ${{ secrets.PORT }}
#            source: "deploy.tar"
#            target: "destination/folder"

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
